[package]
name = "check-macos-updates"
version = "0.1.0"
edition = "2021"
authors = ["Johan Thorén <johan@thoren.xyz>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "check_macos_updates"
path = "src/main.rs"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
psutil = "3.2.2"
